version: '3.6'

services:

  api:
    image: bcgdv/api:latest
    networks:
      - apiSDN
    ports:
      - "${API_HOST_PORT:-5000}:9090"

  db:
    image: postgres:alpine
    networks:
      - apiSDN
    environment:
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres-passwd"
    secrets:
        - postgres-passwd

  adminer:
    image: adminer:latest
    networks:
      - apiSDN
    ports:
      - 8080:8080

networks:
    apiSDN:

secrets:
    postgres-passwd:
        external: true
